Add job-permissions API
godatadriven/databricks-cdk pull request #460
Opened 2022-09-26 14:25 UTC by DaanRademaker

2022-09-26 15:05 UTC, ffinfo requested changes

2022-09-26 15:05 UTC, ffinfo commented on aws-lambda/src/databricks_cdk/resources/permissions/job_permissions.py
> +    action: str = "job-permissions"  #
why the `#`?

2022-09-26 15:05 UTC, ffinfo commented on aws-lambda/src/databricks_cdk/resources/permissions/job_permissions.py
> +    owner_name: str
owner can be a user, group or ServicePrincipal

2022-09-26 15:12 UTC, DaanRademaker commented on aws-lambda/src/databricks_cdk/resources/permissions/job_permissions.py
> +    action: str = "job-permissions"  #
typo!

2022-09-27 13:05 UTC, ffinfo approved these changes

2022-09-27 13:06 UTC, merged